# Generated by Django 5.1.4 on 2024-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='home',
            field=models.IntegerField(verbose_name='номер дома'),
        ),
    ]
