# Generated by Django 5.1.4 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_n_n', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicnetworknode',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
