# Generated by Django 5.1.4 on 2024-12-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_n_n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='модель продукта')),
                ('date', models.DateField(verbose_name='дата выхода продукта на рынок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_n_n.electronicnetworknode', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
